# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'nispaper'

google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'vk', link: 'https://vk.com/public154645189'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '⥢'
  previous_page: '⥤'

sharing_button_prompt: 'Поделитесь:'

related_posts: 'Вам может понравиться:'

post_date_prefix: 'Дата: '
